[versions]
activity = "1.12.2"
agp = "8.13.2"
biometric = "1.2.0-alpha05"
coil = "3.3.0"
# navigation issue with 2025.10.01, 2025.11.00, 2025.11.01, 2025.12.00 wait for fix
compose-bom = "2025.10.00"
compose-accompanist = "0.37.3"
compose-html = "1.1.0"
coroutines = "1.10.2"
datetime = "0.7.1"
desugar = "2.1.5"
hiddenapi-bypass = "6.1"
immutables = "0.4.0"
jackson = "2.20.1"
junit-jupiter = "6.0.1"
koin = "4.1.1"
koin-ksp = "2.3.1"
kotlin = "2.3.0"
ksp = "2.3.4"
ktor = "3.3.3"
leakcanary = "2.14"
libsu = "6.0.0"
lifecycle = "2.10.0"
markdown = "0.7.3"
material = "1.13.0"
navigation = "2.9.6"
navigation3 = "1.0.0"
okhttp = "5.3.2"
preference = "1.2.1"
room = "2.8.4"
serialization = "1.9.0"
shizuku = "13.1.5"
shizuku-hidden = "4.4.0"
shizuku-refine = "4.4.0"
simple-storage = "2.2.0"
# navigation issue related to compose with 2.3.X, wait for fix
vico = "2.2.1"
work = "2.11.0"
zxing = "3.5.4"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
jdk-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutables" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
material = { module = "com.google.android.material:material", version.ref = "material" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-startup = { group = "io.insert-koin", name = "koin-androidx-startup" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-ksp" }
koin-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-ksp" }

coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil" }
coil = { group = "io.coil-kt.coil3", name = "coil" }
coil-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3" }
coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku" }
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku" }
shizuku-hidden = { module = "dev.rikka.hidden:stub", version.ref = "shizuku-hidden" }
shizuku-refine = { module = "dev.rikka.tools.refine:runtime", version.ref = "shizuku-refine" }
hiddenapi-bypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapi-bypass" }
simple-storage = { module = "com.anggrayudi:storage", version.ref = "simple-storage" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }

lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-navigationsuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }
compose-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
compose-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
compose-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-navigation3 = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
compose-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "compose-accompanist" }
compose-html = { module = "be.digitalia.compose.htmlconverter:htmlconverter", version.ref = "compose-html" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

# Test
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
shizuku-refine = { id = "dev.rikka.tools.refine", version.ref = "shizuku-refine" }