[versions]
activity = "1.9.3"
agp = "8.7.1"
biometric = "1.2.0-alpha05"
coil = "2.7.0"
compose-bom = "2024.10.00"
compose-accompanist = "0.36.0"
compose-markdown = "0.5.0"
coroutines = "1.9.0"
immutables = "0.3.8"
jackson = "2.17.2"
koin = "3.5.6"
koin-ksp = "1.3.1"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.25"
ktor = "2.3.12"
leakcanary = "2.14"
libsu = "6.0.0"
lifecycle = "2.8.6"
markdown = "0.7.3"
material = "1.12.0"
navigation = "2.8.3"
okhttp = "5.0.0-alpha.14"
preference = "1.2.1"
room = "2.6.1"
serialization = "1.7.3"
simple-storage = "2.0.0"
work = "2.9.1"
zxing = "3.5.3"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutables" }

work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
material = { module = "com.google.android.material:material", version.ref = "material" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-startup = { group = "io.insert-koin", name = "koin-androidx-startup" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-ksp" }
koin-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-ksp" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
simple-storage = { module = "com.anggrayudi:storage", version.ref = "simple-storage" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }

lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-navigationsuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }
compose-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
compose-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
compose-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "compose-accompanist" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "compose-markdown" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }