name: Omega CI
on:
  push:
    branches: [ A-12 ]
  pull_request:
    branches: [ A-12 ]

jobs:
  send-start-notification:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event_name == 'push'
    steps:
      - name: Send start notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: New push to “Omega Launcher”. Building debug APK…
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.11
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile with Gradle
        run: ./gradlew assembleAospWithQuickstepOmega

      - name: Save name of our Artifact
        id: set-result-artifact
        run: |
          ARTIFACT_PATHNAME_APK=$(ls build/outputs/apk/aospWithQuickstepOmega/debug/*.apk | head -n 1)
          ARTIFACT_NAME_APK=$(basename $ARTIFACT_PATHNAME_APK)
          echo "ARTIFACT_NAME_APK is " ${ARTIFACT_NAME_APK}
          echo "ARTIFACT_PATHNAME_APK=${ARTIFACT_PATHNAME_APK}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME_APK=${ARTIFACT_NAME_APK}" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME_APK }}
          path: ${{ env.ARTIFACT_PATHNAME_APK }}

  send-end-notification:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Get Artifact
        id: get-result-artifact
        run: |
          ARTIFACT_PATH_APK=$(ls /home/runner/work/Omega/Omega/*.apk | head -n 1)
          ARTIFACT_APK=$(basename ARTIFACT_PATH_APK)
          echo "ARTIFACT_PATH_APK=${ARTIFACT_PATH_APK}" >> $GITHUB_ENV
          echo "ARTIFACT_APK=${ARTIFACT_APK}" >> $GITHUB_ENV
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_APK }}
          path: ${{ env.ARTIFACT_PATH_APK }}
      - uses: technote-space/workflow-conclusion-action@v2.1.5
      - name: Send notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: artifacts/debug-apk/**.apk
          message: Build finished with status “${{ env.WORKFLOW_CONCLUSION }}”. Uploading APK if available…
